readData <- "./household_power_consumption.txt"
dataTable <- read.table(readData,header= TRUE, sep = ";")
relevantData <- dataTable[dataTable$Date %in% c("1/2/2007","2/2/2007"),]
timestamp1 <- strptime(paste(relevantData$Date,relevantData$Time,sep=" "),"%d/%m/%Y %H:%M:%S")
gActivePower <- as.numeric( as.character(relevantData$Global_active_power))
voltage <- as.numeric(as.character(relevantData$Voltage))
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2)) 
plot(timestamp1,gActivePower,type="l",ylab="Global Active Power (kilowatts)", xlab="")
plot(timestamp1,voltage,type="l",ylab="Voltage", xlab="datetime")
plot(timestamp1,relevantData$Sub_metering_1,col="green",type="l",ylab="Energy sub metering",ylim=c(0,40),xlab = "")
par(new=TRUE)
plot(timestamp1,relevantData$Sub_metering_2,col="red",type="l",ylim=c(0,40),xlab = "",ylab="")
par(new=TRUE)
plot(timestamp1,relevantData$Sub_metering_3,col="blue",type="l",ylim=c(0,40),xlab = "",ylab="")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("green","red","blue"),lty=1)
gReactivePower <- as.numeric(as.character( relevantData$Global_reactive_power))
plot(timestamp1,gReactivePower,type="l",ylab="Global_reactive_power", xlab="datetime")
dev.off()